
package diary;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author thulasidevi
 */
public class entry extends javax.swing.JFrame {
    
String a;
public entry(String a){
    this.a=a;
}

    public String getA() {
        return a;
    }

    public void setA(String a) {
        this.a = a;
    }
    /** Creates new form entry */
    public entry() {
        initComponents();
        setSize(750,580);
        setBounds(300, 100, 750, 580);
         RegModel m=new RegModel();
        lab_Name.setText(""+m.getName());
        login l=new login();
        lab_Name.setText(""+l.getN());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_date = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        lab_Name = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_entry = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 300));
        getContentPane().setLayout(null);

        txt_date.setDateFormatString("yyyy-MM-dd\n");
        getContentPane().add(txt_date);
        txt_date.setBounds(0, 0, 200, 50);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(null);

        lab_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_Name.setForeground(new java.awt.Color(0, 204, 204));
        lab_Name.setText("jLabel1");
        jPanel1.add(lab_Name);
        lab_Name.setBounds(220, 30, 130, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("FINISH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 500, 190, 30);

        jButton1.setText("GO HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 37, 200, 29);

        jScrollPane1.setViewportView(area_entry);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 70, 620, 420);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slide/events/Cute-kids-tea-party-with-pink-theme.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-10, 10, 740, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 870, 560);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 300);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 190, 140, 130);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 200, 50, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
home h=new home();
h.setVisible(true);
this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String a=area_entry.getText();
        String b=((JTextField)txt_date.getDateEditor().getUiComponent()).getText();
        login l=new login();
        String query = "insert into entry values ('"+a+"','"+b+"','"+l.getN()+"')";
          try {
        Connection c = MySqlConnect.ConnectDB();
        Statement stmt = c.createStatement();
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Saved");
    } catch (Exception e) {
        e.printStackTrace();
    }

       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new entry().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane area_entry;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_Name;
    private com.toedter.calendar.JDateChooser txt_date;
    // End of variables declaration//GEN-END:variables
}
