
package diary;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.*;


public class EventPage extends javax.swing.JFrame {
    
    
       Timer tm;
    int x = 0;
    

    //Images Path In Array
    String[] list = {
        
                        "/home/devi/MY DIARY/src/slide/events/8d5b5f0fe894670fe5c29561db7867d9.jpg",
                        "/home/devi/MY DIARY/src/slide/events/lincolns-inn-fields-holborn-african-algerian-wedding-photographer-hassan-shahara-photography207.jpg",
                        "/home/devi/MY DIARY/src/slide/events/kids-birthday-1024.jpg",
                        
                        
                        "/home/devi/MY DIARY/src/slide/events/4227993.jpg",
                        "/home/devi/MY DIARY/src/slide/events/conferences.jpg",
                      "/home/devi/MY DIARY/src/slide/events/Exmerare-reunião.jpg",//0
                    
                     
                    };
   
        
    
   

    /** Creates new form EventPage */
    public EventPage() {
        
           super("EVENTS");
        jLabel=new JLabel();
        jLabel.setBounds(40, 30, 700, 300);
        setImageSize(5);
        
        tm=new Timer(2000,new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setImageSize(x);
                x+=1;
                if(x>=list.length)
                    x=0;
            }
        });
         
        tm.start();
        
        
        
        initComponents();
        setSize(905,600);
        setBounds(300, 100, 905, 600);
        RegModel m=new RegModel();
        lab_Name.setText(""+m.getName());
        login l=new login();
        lab_Name.setText(""+l.getN());
        
        
        
        
        
        
        
        
    }
    
     public void setImageSize(int i){
        
        ImageIcon icon=new ImageIcon(list[i]);
        Image img=icon.getImage();
        Image newImg=img.getScaledInstance(jLabel.getWidth(), jLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImc=new ImageIcon(newImg);
        jLabel.setIcon(newImc);
        
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        txt_venue = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lab_Name = new javax.swing.JLabel();
        txt_type = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txt_date = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.setMaximumSize(new java.awt.Dimension(327, 327));
        jPanel1.setMinimumSize(new java.awt.Dimension(4000, 3000));
        jPanel1.setPreferredSize(new java.awt.Dimension(4000, 3000));
        jPanel1.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Meeting", "Conference", "Wedding", "Reception", "Party", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(136, 136, 136, 27);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(136, 187, 136, 27);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ADDRESS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(27, 234, 72, 17);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(136, 234, 136, 27);

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setForeground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ADD EVENTS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 40, 98, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("EVENT NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 108, 86, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("DATE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 35, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("EVENT TYPE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 198, 80, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("VENUE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 246, 45, 15);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 283, 120, 30);

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name);
        txt_name.setBounds(202, 96, 479, 30);
        getContentPane().add(txt_venue);
        txt_venue.setBounds(202, 234, 479, 30);

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(712, 0, 172, 550);

        lab_Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_Name.setText("jLabel7");
        getContentPane().add(lab_Name);
        lab_Name.setBounds(10, 11, 169, 22);

        txt_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "MEETING", "CONFERENCE", "WEDDING", "RECEPTION", "PARTY", "ANNIVERSARY", "BIRTHDAY" }));
        txt_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_typeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_type);
        txt_type.setBounds(202, 186, 479, 30);

        jButton2.setText("Go Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 283, 140, 30);

        jLabel.setText("jLabel7");
        getContentPane().add(jLabel);
        jLabel.setBounds(10, 320, 700, 230);
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(200, 300, 0, 0);
        getContentPane().add(txt_date);
        txt_date.setBounds(130, 0, 230, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    
   
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String a=txt_name.getText();
      String b=((JTextField)txt_date.getDateEditor().getUiComponent()).getText();
      String f=txt_type.getSelectedItem().toString();
      String d=txt_venue.getText();
      login l=new login();
      String query="insert into eventz values('"+a+"','"+b+"','"+f+"','"+d+"','"+l.getN()+"')";
       try {
        Connection c = MySqlConnect.ConnectDB();
        Statement stmt = c.createStatement();
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Saved");
    } 
       catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_typeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        home h=new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        new EventPage();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EventPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lab_Name;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextField txt_name;
    private javax.swing.JComboBox txt_type;
    private javax.swing.JTextField txt_venue;
    // End of variables declaration//GEN-END:variables
}
