
package diary;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author thulasidevi
 */
public class password extends javax.swing.JFrame {

    /** Creates new form password */
    public password() {
        initComponents();
        setSize(700,570);
        setBounds(300, 100, 700, 570);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pass_current = new javax.swing.JPasswordField();
        pass_new = new javax.swing.JPasswordField();
        pass_retype = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel1.setText("CURRENT PASSWORD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(64, 102, 190, 19);

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel2.setText("NEW PASSWORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(64, 156, 190, 19);

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel3.setText("RE-TYPE PASSWORD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(64, 194, 190, 19);
        jPanel1.add(pass_current);
        pass_current.setBounds(262, 102, 150, 30);
        jPanel1.add(pass_new);
        pass_new.setBounds(262, 146, 150, 30);

        pass_retype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_retypeActionPerformed(evt);
            }
        });
        jPanel1.add(pass_retype);
        pass_retype.setBounds(262, 194, 150, 30);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 240, 130, 40);

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel4.setText("USERNAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(64, 71, 160, 19);
        jPanel1.add(txt_username);
        txt_username.setBounds(262, 61, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("CHANGE PASSWORD");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(114, 11, 206, 33);

        jButton2.setText("GO HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 240, 140, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slide/events/password.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 810, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void pass_retypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_retypeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pass_retypeActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String u_name=txt_username.getText();
String current=pass_current.getText();
String pnew=pass_new.getText();
 RegModel m=new RegModel();
 m.setUserName(u_name);
String retype=pass_retype.getText();
if(pnew.equals(retype)){
    Connection conn=null;
        PreparedStatement pstmt=null;
        //ResultSet rs=null;
        try{
           
            Class.forName("com.mysql.jdbc.Driver");
           conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/diary","root","password");
            System.out.println(""+pnew);
            System.out.println(""+m.getUserName());
           pstmt=(PreparedStatement) conn.prepareStatement("update reg set Password=? where UserName='"+m.getUserName()+"'");
            pstmt.setString(1, pnew);
            
          
           pstmt.executeUpdate();
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                 conn.close();
            pstmt.close();
             
            }
          catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }
        }      
        
 JOptionPane.showMessageDialog(rootPane, "Updated ");
}
else
{
JOptionPane.showMessageDialog(rootPane, "Re-enter details");
}
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       home h=new home();
       h.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new password().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass_current;
    private javax.swing.JPasswordField pass_new;
    private javax.swing.JPasswordField pass_retype;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
