
package diary;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Icon.*;
import javax.swing.ImageIcon;
/**
 *
 * @author thulasidevi
 */
public class profile extends javax.swing.JFrame {

    /** Creates new form profile */
    public profile() {
        initComponents();
        setSize(790,620);
        setBounds(300, 100, 790, 620);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txt_dob = new javax.swing.JTextField();
        txt_skills = new javax.swing.JTextField();
        txt_hobbies = new javax.swing.JTextField();
        txt_interest = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        txt_father = new javax.swing.JTextField();
        txt_mother = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_occupation = new javax.swing.JTextField();
        txt_nickname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("MY PROFILE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(153, 13, 91, 17);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(null);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 460, 100, 29);
        jPanel1.add(txt_dob);
        txt_dob.setBounds(199, 428, 130, 27);
        jPanel1.add(txt_skills);
        txt_skills.setBounds(199, 397, 130, 27);
        jPanel1.add(txt_hobbies);
        txt_hobbies.setBounds(199, 366, 130, 27);
        jPanel1.add(txt_interest);
        txt_interest.setBounds(199, 335, 130, 27);

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(199, 218, 140, 79);

        txt_father.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fatherActionPerformed(evt);
            }
        });
        jPanel1.add(txt_father);
        txt_father.setBounds(199, 187, 136, 27);

        txt_mother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_motherActionPerformed(evt);
            }
        });
        jPanel1.add(txt_mother);
        txt_mother.setBounds(199, 156, 136, 27);
        jPanel1.add(txt_age);
        txt_age.setBounds(199, 125, 136, 27);
        jPanel1.add(txt_occupation);
        txt_occupation.setBounds(199, 94, 136, 27);

        txt_nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicknameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nickname);
        txt_nickname.setBounds(199, 66, 136, 27);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 255));
        jLabel12.setText("DATE OF BIRTH");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(51, 431, 130, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setText("SKILLS");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(51, 400, 110, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 255));
        jLabel10.setText("HOBBIES");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(51, 369, 120, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setText("INTERESTS");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(51, 338, 120, 14);

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("PERSONAL");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(51, 307, 82, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("ADDRESS");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(51, 218, 130, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("FATHER'S NAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(51, 190, 130, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("MOTHER'S NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(51, 159, 130, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("AGE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(51, 128, 80, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("OCCUPATION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(51, 97, 110, 14);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("NICKNAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(51, 69, 100, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 255));
        jLabel13.setText("USERNAME");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(51, 46, 100, 14);
        jPanel1.add(txt_username);
        txt_username.setBounds(199, 40, 136, 27);

        jButton2.setText("GO HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(189, 459, 130, 29);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slide/cute-girly-wallpapers-hd-620x388.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(350, 120, 410, 290);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 870, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txt_nicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicknameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_nicknameActionPerformed

private void txt_motherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_motherActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_motherActionPerformed

private void txt_fatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fatherActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_fatherActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String NickName=txt_nickname.getText();
String Occupation=txt_occupation.getText();
String Age=txt_age.getText();
String Father=txt_father.getText();
String Mother=txt_mother.getText();
String Address=txt_address.getText();
String Interest=txt_interest.getText();
String Hobbies=txt_hobbies.getText();
String Skills=txt_skills.getText();
String DOB=txt_dob.getText();
String UserName=txt_username.getText();



ProfModel m=new ProfModel(NickName,Occupation,Age,Father,Mother,Address,Interest,Hobbies,Skills,DOB,UserName);

m.setNickName(NickName);
m.setOccupation(Occupation);
m.setAge(Age);
m.setFather(Father);
m.setMother(Mother);
m.setAddress(Address);
m.setInterest(Interest);
m.setHobbies(Hobbies);
m.setSkills(Skills);
m.setDOB(DOB);
m.setUserName(UserName);


try{
    int add=ProfController.add(m);
    if(add>0){
        JOptionPane.showMessageDialog(rootPane, "Registered Successfully..");
        
    }
    
}
catch(ClassNotFoundException e){
    e.printStackTrace();
}
catch(SQLException e){
    e.printStackTrace();
}
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       home h=new home();
       h.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new profile().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_father;
    private javax.swing.JTextField txt_hobbies;
    private javax.swing.JTextField txt_interest;
    private javax.swing.JTextField txt_mother;
    private javax.swing.JTextField txt_nickname;
    private javax.swing.JTextField txt_occupation;
    private javax.swing.JTextField txt_skills;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
String filename=null;
int s=0;
byte [] person_image=null;
}

