/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProfilePage.java
 *
 * Created on 22-Aug-2016, 01:42:23
 */
package diary;



import java.sql.*;
import javax.swing.JOptionPane;
import com.mysql.jdbc.PreparedStatement;

/**
 *
 * @author thulasidevi
 */
public class ProfilePage extends javax.swing.JFrame {

    /** Creates new form ProfilePage */
    public ProfilePage() {
        initComponents();
        setBounds(300, 100, 750, 620);
        
        login l=new login();
        String j=l.getN();
        Connection conn=null;
        PreparedStatement pstmt=null;
        ResultSet rs=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
           conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/diary","root","password");
            
           pstmt=(PreparedStatement) conn.prepareStatement("select * from reg,prof where reg.`UserName`=? and prof.`Username`=?");
            pstmt.setString(1, j);
            pstmt.setString(2, j);
          
            rs=pstmt.executeQuery();
            while(rs.next()){
                lab_name.setText(rs.getString("Name"));
                lab_age.setText(rs.getString("Age"));
                lab_father.setText(rs.getString("Father"));
                lab_mother.setText(rs.getString("Mother"));
                lab_occupation.setText(rs.getString("Occupation"));
                lab_address.setText(rs.getString("Address"));
                lab_dob.setText(rs.getString("DOB"));
                lab_skills.setText(rs.getString("Skills"));
                lab_interests.setText(rs.getString("Interest"));
                lab_hobbies.setText(rs.getString("Hobbies"));
                lab_nickname.setText(rs.getString("NickName"));
                lab_email.setText(rs.getString("EmailId"));
                lab_phone.setText(rs.getString("PhoneNumber"));
                
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                 conn.close();
            pstmt.close();
            rs.close(); 
            }
          catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }
        }      
        
       
              
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lab_name = new javax.swing.JLabel();
        lab_nickname = new javax.swing.JLabel();
        lab_age = new javax.swing.JLabel();
        lab_occupation = new javax.swing.JLabel();
        lab_father = new javax.swing.JLabel();
        lab_mother = new javax.swing.JLabel();
        lab_interests = new javax.swing.JLabel();
        lab_hobbies = new javax.swing.JLabel();
        lab_skills = new javax.swing.JLabel();
        lab_dob = new javax.swing.JLabel();
        lab_email = new javax.swing.JLabel();
        lab_phone = new javax.swing.JLabel();
        lab_address = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(109, 74, 36, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NickName");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(86, 99, 63, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(119, 124, 24, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Occupation");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(78, 144, 73, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Father");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(104, 169, 42, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mother");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 194, 45, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(95, 369, 51, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Interests");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(88, 219, 57, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hobbies");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(96, 244, 52, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Skills");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(112, 269, 34, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DOB");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(118, 294, 28, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email ID");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(95, 319, 52, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Phone Number");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(59, 344, 93, 14);

        jButton1.setText("GO HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(212, 449, 160, 29);

        lab_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_name.setForeground(new java.awt.Color(0, 204, 204));
        lab_name.setText("jLabel14");
        jPanel1.add(lab_name);
        lab_name.setBounds(212, 74, 157, 14);

        lab_nickname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_nickname.setForeground(new java.awt.Color(0, 204, 204));
        lab_nickname.setText("jLabel14");
        jPanel1.add(lab_nickname);
        lab_nickname.setBounds(212, 99, 157, 14);

        lab_age.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_age.setForeground(new java.awt.Color(0, 204, 204));
        lab_age.setText("jLabel15");
        jPanel1.add(lab_age);
        lab_age.setBounds(212, 124, 157, 14);

        lab_occupation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_occupation.setForeground(new java.awt.Color(0, 204, 204));
        lab_occupation.setText("jLabel15");
        jPanel1.add(lab_occupation);
        lab_occupation.setBounds(212, 144, 157, 14);

        lab_father.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_father.setForeground(new java.awt.Color(0, 204, 204));
        lab_father.setText("jLabel15");
        jPanel1.add(lab_father);
        lab_father.setBounds(212, 169, 157, 14);

        lab_mother.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_mother.setForeground(new java.awt.Color(0, 204, 204));
        lab_mother.setText("jLabel15");
        jPanel1.add(lab_mother);
        lab_mother.setBounds(212, 194, 157, 14);

        lab_interests.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_interests.setForeground(new java.awt.Color(0, 204, 204));
        lab_interests.setText("jLabel15");
        jPanel1.add(lab_interests);
        lab_interests.setBounds(212, 219, 157, 14);

        lab_hobbies.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_hobbies.setForeground(new java.awt.Color(0, 204, 204));
        lab_hobbies.setText("jLabel15");
        jPanel1.add(lab_hobbies);
        lab_hobbies.setBounds(212, 244, 157, 14);

        lab_skills.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_skills.setForeground(new java.awt.Color(0, 204, 204));
        lab_skills.setText("jLabel15");
        jPanel1.add(lab_skills);
        lab_skills.setBounds(212, 269, 157, 14);

        lab_dob.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_dob.setForeground(new java.awt.Color(0, 204, 204));
        lab_dob.setText("jLabel15");
        jPanel1.add(lab_dob);
        lab_dob.setBounds(212, 294, 157, 14);

        lab_email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_email.setForeground(new java.awt.Color(0, 204, 204));
        lab_email.setText("jLabel15");
        jPanel1.add(lab_email);
        lab_email.setBounds(212, 319, 157, 14);

        lab_phone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_phone.setForeground(new java.awt.Color(0, 204, 204));
        lab_phone.setText("jLabel15");
        jPanel1.add(lab_phone);
        lab_phone.setBounds(212, 344, 157, 14);

        lab_address.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lab_address.setForeground(new java.awt.Color(0, 204, 204));
        lab_address.setText("jLabel25");
        jPanel1.add(lab_address);
        lab_address.setBounds(212, 369, 157, 69);

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 255, 204));
        jLabel26.setText("MY PROFILE");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(220, 11, 177, 36);

        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(430, 380, 240, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        home h=new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ProfilePage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lab_address;
    private javax.swing.JLabel lab_age;
    private javax.swing.JLabel lab_dob;
    private javax.swing.JLabel lab_email;
    private javax.swing.JLabel lab_father;
    private javax.swing.JLabel lab_hobbies;
    private javax.swing.JLabel lab_interests;
    private javax.swing.JLabel lab_mother;
    private javax.swing.JLabel lab_name;
    private javax.swing.JLabel lab_nickname;
    private javax.swing.JLabel lab_occupation;
    private javax.swing.JLabel lab_phone;
    private javax.swing.JLabel lab_skills;
    // End of variables declaration//GEN-END:variables
}
